// netlify/functions/send-pdf.js

const sgMail = require("@sendgrid/mail");
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

exports.handler = async (event) => {
  // 1) Validate the shared secret header
  if (event.headers["x-api-key"] !== process.env.FUNC_API_KEY) {
    return { statusCode: 401, body: "Unauthorized" };
  }

  // 2) Parse the incoming JSON
  const { customer, pdfDataUri } = JSON.parse(event.body);

  // 3) Strip off the "data:application/pdf;base64," prefix
  const base64 = pdfDataUri.split(",")[1];

  // 4) Build the email with attachment
  const msg = {
    to:   "your.team@muriphys.com",
    from: "no-reply@muriphys.com",
    subject: `New PDF from ${customer.name || "Unknown"}`,
    text:    `You’ve got a new PDF generated by ${customer.name} <${customer.email}>.`,
    attachments: [{
      content:     base64,
      filename:    "Muriphys_Project_Summary.pdf",
      type:        "application/pdf",
      disposition: "attachment"
    }]
  };

  // 5) Send via SendGrid
  try {
    await sgMail.send(msg);
    return { statusCode: 200, body: "Email sent" };
  } catch (err) {
    console.error("SendGrid error:", err);
    return { statusCode: 500, body: "Failed to send email" };
  }
};